-- Tạo cơ sở dữ liệu "QUAN_LI_CONG_TAC_BANHANG"
CREATE DATABASE QUAN_LI_CONG_TAC_BAN_HANG;

DROP TABLE IF EXISTS KHACHANG;
DROP TABLE IF EXISTS DONDATHANG;
DROP TABLE IF EXISTS NHANVIEN;
DROP TABLE IF EXISTS CHITIETDONHANG;
DROP TABLE IF EXISTS MATHANG;
DROP TABLE IF EXISTS NHACUNGCAP;
DROP TABLE IF EXISTS LOAIHANG;
-- Tạo bảng "KHACHHANG"
CREATE TABLE KHACHANG (
   MAKHACHHANG INT PRIMARY KEY,
   TENCONGTY VARCHAR(50),
   TENGIAODICH VARCHAR(50),
   DIACHI VARCHAR(50),
   EMAIL VARCHAR(50),
   DIENTHOAI VARCHAR(10),
   FAX VARCHAR(50)
);

-- Tạo bảng "NHANVIEN"
CREATE TABLE NHANVIEN (
   MANHANVIEN INT PRIMARY KEY,
   HO VARCHAR(10),
   TEN VARCHAR(10),
   NGAYSINH DATE,
   DIACHI VARCHAR(30),
   NGAYLAMVIEC DATE,
   LUONGCOBAN DECIMAL(10, 2),
   PHUCAP VARCHAR(10)
);

-- Tạo bảng "DONDATHANG"
CREATE TABLE DONDATHANG (
    SOHOADON INT PRIMARY KEY,
	MAKHACHHANG INT,
	MANHANVIEN INT,
	NGAYDATHANG DATE,
	NGAYGIAOHANG DATE,
	NGAYCHUYENHANG DATE,
	NOIGIAOHANG VARCHAR(50),
	FOREIGN KEY (MAKHACHHANG) REFERENCES KHACHANG(MAKHACHHANG),
	FOREIGN KEY (MANHANVIEN) REFERENCES NHANVIEN(MANHANVIEN),
);

-- Tạo bảng "NHACUNGCAP"
CREATE TABLE NHACUNGCAP (
	MACONGTY VARCHAR(10) PRIMARY KEY,
	TENCONGTY VARCHAR(50), 
	TENGIAODICH VARCHAR(50),
	DIACHI VARCHAR(50),
	DIENTHOAI VARCHAR(15) -- Sử dụng VARCHAR cho số điện thoại
);
-- Tạo bảng "LOAIHANG"
CREATE TABLE LOAIHANG (
	MALOAIHANG INT PRIMARY KEY,
	TENLOAIHANG VARCHAR(50)
);

-- Tạo bảng "MATHANG"
CREATE TABLE MATHANG (
	MAHANG VARCHAR(10) PRIMARY KEY,
	TENHANG VARCHAR(50),
	MACONGTY VARCHAR(10),
	MALOAIHANG INT,
	SOLUONG INT,
	DONVITINH VARCHAR(10),
	GIAHANG DECIMAL(10, 2)
	FOREIGN KEY(MACONGTY) REFERENCES NHACUNGCAP(MACONGTY),
	FOREIGN KEY(MALOAIHANG) REFERENCES LOAIHANG(MALOAIHANG)
);

-- Tạo bảng "CHITIETDAHANG"
CREATE TABLE CHITIETDATHANG (
	SOHOADON INT,
	MAHANG VARCHAR(10),
	PRIMARY KEY (SOHOADON, MAHANG),
	GIABAN DECIMAL(10, 2),
	SOLUONG INT,
	MUCGIAMGIA INT,
	FOREIGN KEY (SOHOADON) REFERENCES DONDATHANG(SOHOADON),
	FOREIGN KEY(MAHANG) REFERENCES MATHANG(MAHANG)
);	



